import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  icons: "/icons/logo.svg",
  title: "Yoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="relative bg-dark-400 text-white"
      >
        {children}
      </body>
    </html>
  );
}
