import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  icons: "/icons/logo.svg",
  title: "Yoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          baseTheme: dark,
          layout: { logoImageUrl: "/icons/yoom-logo.svg" },
        }}
      >
        <body className="relative bg-dark-400 text-white">{children}</body>
      </ClerkProvider>
    </html>
  );
}
